# Generated by Django 3.0 on 2019-12-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191211_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to='tasks.User', verbose_name='User'),
        ),
    ]
